### ISSUE TITLE
Randomizer doesn't support the current game version.

### ISSUE THREAD

**Issue by Dutchball8** [pawREP/ZHM5Randomizer#20]

**Comment by Dutchball8** [comment]
the version simply doesn't work for me, I've redownloaded the files and updated my game, but it still doesn't work

**Comment by Mahdix6x9x** [comment]
When I install version 1.33 above it says the randomizer doesn't support the game version,
I used the 1.32 version below and it works but at the start it has the 0x00142 error again.
I don't know what do do 
I have steam and I have added the game and launched it but it doesn't work again because my steam is offline supported.
I think my pc needs a special software or something special. Anyone has any IDEA?

**Comment by pawREP** [comment]
Assuming this is about Hitman 3. The issue us fixed with 39ed69f6c1c6ff44c38ef36d09b4fe33b7187923, download the latest release.
